stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  image: alpine:latest
  script:
    - echo "Проверка наличия каталогов dags/ и spark/..."
    - test -d dags || { echo "Каталог dags/ не найден"; exit 1; }
    - test -d spark || { echo "Каталог spark/ не найден"; exit 1; }
  rules:
    - when: always

build-job:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "Сборка Docker образа..."
    - ls -la
    - docker build -t your_image_name .
  rules:
    # Если имя ветки начинается с "feature/", сборка запускается вручную
    - if: '$CI_COMMIT_REF_NAME =~ /^feature\//'
      when: manual
    - when: on_success

deploy-job:
  stage: deploy
  image: tmaier/docker-compose:latest
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "Деплой приложения..."
    - docker-compose rm -sf
    - docker-compose up -d
    - echo "Приложение успешно задеплоено!"
  rules:
    # Деплой запускается автоматически только для веток main, master и develop
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop"'
      when: on_success
    - when: never

clear-job:
  stage: deploy
  image: tmaier/docker-compose:latest
  script:
    - docker-compose rm -sf
  rules:
    - when: manual
