version: '3.7'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    env_file: .env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - gitlab-network
        
networks:
  gitlab-network:
    external: true
