server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push # адрес Loki, куда будут слаться логи
scrape_configs:
- job_name: system # любое имя
  static_configs:
  - targets:
      - localhost # поскольку мы монтируем папку с логами прямо в контейнер Loki, он считается что собирает логи со своей локальной файловой
    labels:
      job: airflow_logs # любое имя, по этому полю будет осуществляться индексирование
      __path__: /opt/airflow/logs/dag_id*/run_id*/task_id*/*.log # для Loki необязательно указывать полный путь, главное сказать ему, где искать log